version: '3.8'

services:
  app:
    build: backend/.
    container_name: desafio_app
    volumes:
      - ./backend:/var/www
      - /var/www/storage
      - /var/www/bootstrap/cache
    networks:
      - desafio
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: desafio_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - desafio
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: desafio_db
    environment:
      MYSQL_DATABASE: desafio_fullstack
      MYSQL_USER: desafio_fullstack
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - desafio

networks:
  desafio:
    driver: bridge
