version: '3.8'

services:
  backend:
    build: backend/.
    container_name: desafio_backend
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
      - /var/www/storage
      - /var/www/bootstrap/cache
    ports:
      - "9000:9000"
    networks:
      - desafio
    depends_on:
      - db
    # command: sh -c "php artisan migrate --force"

  frontend:
    build: frontend/.
    container_name: desafio_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - desafio
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    container_name: desafio_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - desafio
    depends_on:
      - backend
      - frontend

  db:
    image: mysql:8.0
    container_name: desafio_db
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: desafio_fullstack
      MYSQL_USER: desafio_fullstack
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    # command: --default-authentication-plugin=mysql_native_password --ssl-mode=DISABLED
    # ports:
      # - "3306:3306"
    networks:
      - desafio

networks:
  desafio:
    driver: bridge
